blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from service.apps import ServiceConfig
from service.views import (HomeTemplateView, CustomerListView, MailingListView, MessageListView, MessageDetailView,
                           MailingCreateView, MessageDeleteView, CustomerCreateView, CustomerDetailView,
                           CustomerUpdateView, CustomerDeleteView, MessageCreateView, MessageUpdateView,
                           MailingDetailView, MailingUpdateView, MailingDeleteView, get_report, LogListView,
                           mailing_toggle_activity)

app_name = ServiceConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),

    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customers/<slug:slug>/', CustomerDetailView.as_view(), name='customer'),
    path('customers/<slug:slug>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customers/<slug:slug>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),

    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<slug:slug>/', MessageDetailView.as_view(), name='message'),
    path('messages/<slug:slug>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<slug:slug>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('services/', MailingListView.as_view(), name='mailings'),
    path('services/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('services/<slug:slug>/', MailingDetailView.as_view(), name='mailing'),
    path('services/<slug:slug>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('services/<slug:slug>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('report/', get_report, name='report'),
    path('services/<slug:slug>/logs/', LogListView.as_view(), name='logs'),
    path('services/<slug:slug>/activity/', mailing_toggle_activity, name='mailing_activity'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserProfile, email_verification, password_recovery, \
    UserListView, user_toggle_activity, UserDitailView, UserDeleteView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user/<int:pk>/', UserDitailView.as_view(), name='user'),
    path('profile/', UserProfile.as_view(), name='profile'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('verification/', email_verification, name='verification'),
    path('recovery/', password_recovery, name='recovery'),
    path('list/', UserListView.as_view(), name='users_list'),
    path('user/activity/<int:pk>/', user_toggle_activity, name='user_activity'),
]

users/models.py
from slugify import slugify

from django.contrib.auth.models import AbstractUser
from django.db import models

from service.models import NULLABLE


class User(AbstractUser):
    """Модель для работы с пользователями"""

    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    key = models.CharField(max_length=12, verbose_name='Ключ для верификации почты', **NULLABLE)
    is_verified = models.BooleanField(default=False, verbose_name='Почта верифицирована')
    slug = models.SlugField(unique=True, verbose_name='slug')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.email})'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('pk',)
        permissions = [
            (
                'set_is_active_user',   # Разрешение на блокировку/активацию пользователя
                'Can active Пользователь'
            )
        ]

    def save(self, *args, **kwargs):
        """Создает уникальный slug для пользователя"""

        self.slug = slugify(self.email)
        base_slug = self.slug
        num = 1
        while User.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from service.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма для регистрации пользователей"""

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    """Форма для редактирования пользователей"""

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """Удаление поля 'password' из формы"""

        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from config import settings
from users.forms import UserRegisterForm, UserForm
from users.models import User


class RegisterView(CreateView):
    """Контроллер для регистрации пользователя"""

    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        """
        Создает пароль для подтверждения email, сохраняет его в объекте пользователя
        и отправляет на email указанный при регистрации.
        Сохраняет пользователя в группе user.
        """

        user = form.save()
        key = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        user.key = key
        user.save()
        send_mail(
            subject='Подтверждение электронной почты',
            message=f'Код для подтверждения: {key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        group = Group.objects.get(name='users')
        group.user_set.add(user)
        return super().form_valid(form)


class LoginView(BaseLoginView):
    """Контроллер для входа пользователя"""

    template_name = 'users/login.html'

    def get_success_url(self):
        """
        Если email пользователя верифицирован, перенаправляет на главную страницу,
        иначе перенаправляет на страницу верификации email.
        """

        user = self.request.user
        if user.is_verified:
            return reverse('service:home')
        return reverse('users:verification')


class LogoutView(BaseLogoutView):
    """Контроллер для выхода пользователя"""

    pass


class UserDitailView(LoginRequiredMixin, DetailView):
    """Контроллер для вывода информации о пользователе"""

    model = User

    def get_context_data(self, **kwargs):
        """Сохраняет в context_data текущего авторизованного пользователя"""

        context_data = super().get_context_data(**kwargs)
        context_data['user'] = self.request.user
        return context_data


class UserProfile(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования своего профиля текущим пользователем"""

    model = User
    form_class = UserForm

    def get_object(self, queryset=None):
        """Возвращает объект текущего пользователя"""

        return self.request.user

    def get_success_url(self):
        """Возвращает на страницу вывода информации о пользователе"""

        return reverse('users:user', args=[self.object.id])


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер для редактирования пользователя"""

    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:users_list')

    def test_func(self):
        """Задает доступ к редактированию пользователя только для суперпользователя"""

        return self.request.user.is_superuser


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер для удаления пользователя"""

    model = User
    success_url = reverse_lazy('users:users_list')

    def test_func(self):
        """Задает доступ к удалению пользователя только для суперпользователя"""

        return self.request.user.is_superuser


@login_required
def email_verification(request):
    """
    Верифицирует email пользователя. Если введенный пользователем код не верный, перенаправляет на
    страницу где сообщается что код не верный. Если код верный, перенаправляет на страницу где сообщается
    что код верный и устанавливает True в поле 'is_verified' пользователя.
    """

    if request.method == 'POST':
        input_key = request.POST.get('key')
        try:
            user = User.objects.get(key=input_key)
            user.is_verified = True
            user.save()
        except User.DoesNotExist:
            return render(request, 'users/unsuccessful_verification.html')
        return render(request, 'users/successful_verification.html')
    return render(request, 'users/verification.html')


def password_recovery(request):
    """
    Формирует новый пароль и пытается выслать его на email введенный пользователем.
    Если пользователь с таким email не зарегистрирован, перенаправляет на страницу где об этом сообщается.
    Если пользователь найден, высылает на его email новый пароль.
    """

    if request.method == 'POST':
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        input_email = request.POST.get('email')
        try:
            user = User.objects.get(email=input_email)
            user.set_password(new_password)
            user.save()
            send_mail(
                subject='Восстановление доступа',
                message=f'Ваш новый пароль: {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        except User.DoesNotExist:
            return render(request, 'users/unsuccessful_recovery.html')
        return render(request, 'users/successful_recovery.html')
    return render(request, 'users/password_recovery.html')


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Контроллер для вывода списка пользователей"""

    model = User

    def test_func(self):
        """Задает доступ к списку пользователей только для суперпользователя или менеджера"""

        user = self.request.user
        is_superuser = user.is_superuser
        groups = user.groups.filter(name__in=['managers']).exists()
        return is_superuser or groups


@login_required
@permission_required('users.set_is_active_user')
def user_toggle_activity(request, pk):
    """Блокирует/активирует пользователя"""

    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect('users:users_list')

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Авторизация пользователя
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a class="p-2 btn btn-outline-primary" href="{% url 'service:home' %}">Отмена</a>
                    <a class="p-2 btn btn-outline-warning" href="{% url 'users:recovery' %}">Забыли пароль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Восстановление пароля
                    </h3>
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="email" class="form-control" id="email"
                                   placeholder="Введите email"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary">Восстановить</button>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Регистрация пользователя</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a class="p-2 btn btn-outline-primary" href="{% url 'service:home' %}">Отмена</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/successful_recovery.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-4">Новый пароль выслан вам на email</h3>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти с новым паролем</a>
    </div>
{% endblock %}

users/templates/users/successful_verification.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-4">Электронная почта подтверждена</h3>
        <a class="p-2 btn btn-outline-primary" href="{% url 'service:home' %}">На главную</a>
    </div>
{% endblock %}

users/templates/users/unsuccessful_recovery.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-4">Пользователь с таким email не зарегистрирован</h3>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:recovery' %}">Попробовать снова</a>
    </div>
{% endblock %}

users/templates/users/unsuccessful_verification.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-4">Не верный код</h3>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:verification' %}">Ввести снова</a>
    </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3>Удаление пользователя</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить пользователя "{{ object.email }}"</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'users:users_list'%}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">{{ object.email }}</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">ФИО</th>
            <th scope="col">Телефон</th>
            <th scope="col">Аватар</th>
            <th scope="col">Почта верифицирована</th>
            <th scope="col">Активность</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.pk }}</td>
            <td>{{ object.first_name }} {{ object.last_name }}</td>
            {% if object.phone %}
                <td>{{ object.phone }}</td>
            {% else %}
                <td>Не указан</td>
            {% endif %}
            <td>{{ object.avatar }}</td>

            {% if object.is_verified %}
                <td>Да</td>
            {% else %}
                <td>Нет</td>
            {% endif %}


            {% if object.is_active %}
                <td>Активен</td>
            {% else %}
                <td>Заблокирован</td>
            {% endif %}
            <td>
                {% if perms.users.change_user %}
                    <a class="btn btn-outline-warning"
                       href="{% url 'users:user_update' object.pk %}">Редактировать</a>
                {% endif %}

                {% if perms.users.delete_user %}
                    <a class="btn btn-outline-danger" href="{% url 'users:user_delete' object.pk %}">Удалить</a>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                      <a class="p-2 btn btn-outline-primary" href="{% url 'service:home' %}">Выход</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'base.html' %}

{% block content %}
    <h2 align="center">Пользователи</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Email</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилие</th>
            <th scope="col">Телефон</th>
            <th scope="col">Активность</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>
                    <a href="{% url 'users:user' object.pk %}">{{ object.email }}</a>
                </td>
                <td>{{ object.first_name }}</td>
                <td>{{ object.last_name }}</td>
                {% if object.phone %}
                    <td>{{ object.phone }}</td>
                {% else %}
                    <td>Не указан</td>
                {% endif %}
                <td>
                    {% if object.is_active %}
                        Активен
                    {% else %}
                        Заблокирован
                    {% endif %}
                </td>
                {% if perms.users.set_is_active_user %}
                    <td>
                        {% if object.is_active %}
                            <a class="btn btn-outline-danger"
                               href="{% url 'users:user_activity' object.pk %}">Заблокировать</a>
                        {% else %}
                            <a class="btn btn-outline-success"
                               href="{% url 'users:user_activity' object.pk %}">Активировать</a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

users/templates/users/verification.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Подтверждение электронной почты
                    </h3>
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="key" class="form-control" id="key"
                                   placeholder="Введите код из письма"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                        <a class="p-2 btn btn-outline-warning" href="{% url 'service:home' %}">Подтвердить
                            позже</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}