blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from service.apps import ServiceConfig
from service.views import (HomeTemplateView, CustomerListView, MailingListView, MessageListView, MessageDetailView,
                           MailingCreateView, MessageDeleteView, CustomerCreateView, CustomerDetailView,
                           CustomerUpdateView, CustomerDeleteView, MessageCreateView, MessageUpdateView,
                           MailingDetailView, MailingUpdateView, MailingDeleteView, get_report, LogListView,
                           mailing_toggle_activity)

app_name = ServiceConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),

    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customers/<slug:slug>/', CustomerDetailView.as_view(), name='customer'),
    path('customers/<slug:slug>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customers/<slug:slug>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),

    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<slug:slug>/', MessageDetailView.as_view(), name='message'),
    path('messages/<slug:slug>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<slug:slug>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('services/', MailingListView.as_view(), name='mailings'),
    path('services/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('services/<slug:slug>/', MailingDetailView.as_view(), name='mailing'),
    path('services/<slug:slug>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('services/<slug:slug>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('report/', get_report, name='report'),
    path('services/<slug:slug>/logs/', LogListView.as_view(), name='logs'),
    path('services/<slug:slug>/activity/', mailing_toggle_activity, name='mailing_activity'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserProfile, email_verification, password_recovery, \
    UserListView, user_toggle_activity, UserDitailView, UserDeleteView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user/<int:pk>/', UserDitailView.as_view(), name='user'),
    path('profile/', UserProfile.as_view(), name='profile'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('verification/', email_verification, name='verification'),
    path('recovery/', password_recovery, name='recovery'),
    path('list/', UserListView.as_view(), name='users_list'),
    path('user/activity/<int:pk>/', user_toggle_activity, name='user_activity'),
]

service/models.py
from slugify import slugify

from django.db import models

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Customer(models.Model):
    """Модель для работы с клиентами"""

    name = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='customer',
                             verbose_name='Пользователь')

    def __str__(self):
        return f"{self.name} ({self.email})"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для клиента"""

        self.slug = slugify(self.email)
        base_slug = self.slug
        num = 1
        while Customer.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Message(models.Model):
    """Модель для работы с сообщениями"""

    topic = models.CharField(max_length=200, verbose_name='Тема письма')
    body = models.TextField(**NULLABLE, verbose_name='Содержимое письма')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='message',
                             verbose_name='Пользователь')

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для сообщения"""

        self.slug = slugify(self.topic)
        base_slug = self.slug
        num = 1
        while Message.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Mailing(models.Model):
    """Модель для работы с рассылками"""

    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    start = models.TimeField(default='00:00:00', verbose_name='Время начала рассылки')
    finish = models.TimeField(default='00:00:00', verbose_name='Время окончания рассылки')
    day = models.BooleanField(default=False, verbose_name='Раз в день')
    week = models.BooleanField(default=False, verbose_name='Раз в неделю')
    month = models.BooleanField(default=False, verbose_name='Раз в месяц')
    status = models.CharField(**NULLABLE, max_length=150, verbose_name='Статус рассылки')
    customers = models.ManyToManyField(Customer, related_name='mailing', verbose_name='Клиенты')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name='mailing', **NULLABLE,
                                verbose_name='Сообщение')
    is_active = models.BooleanField(default=True, verbose_name='Активная')
    next_run = models.DateField(**NULLABLE, verbose_name='Дата следующей рассылки')
    slug = models.SlugField(unique=True, verbose_name='slug')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE, related_name='mailing',
                             verbose_name='Пользователь')

    def __str__(self):
        return f"{self.message}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('pk',)
        permissions = [
            (
                'set_is_active_mailing',
                'Can active Рассылка'
            )
        ]

    def save(self, *args, **kwargs):
        """Создает уникальный slug для рассылки"""

        self.slug = slugify(self.message.topic)
        base_slug = self.slug
        num = 1
        while Mailing.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)


class Log(models.Model):
    """Модель для работы с логами рассылок"""

    date_time_last_attempt = models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')
    attempt_status = models.CharField(max_length=150, verbose_name='Статус попытки')
    mail_server_response = models.CharField(max_length=150, verbose_name='Ответ почтового сервера')
    slug = models.SlugField(unique=True, verbose_name='slug')
    mailing = models.ForeignKey(Mailing, on_delete=models.SET_NULL, **NULLABLE, related_name='log',
                                verbose_name='Рассылка')

    def __str__(self):
        return f"{self.date_time_last_attempt} {self.attempt_status}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

    def save(self, *args, **kwargs):
        """Создает уникальный slug для лога"""

        self.slug = slugify(self.attempt_status)
        base_slug = self.slug
        num = 1
        while Log.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)

users/models.py
from slugify import slugify

from django.contrib.auth.models import AbstractUser
from django.db import models

from service.models import NULLABLE


class User(AbstractUser):
    """Модель для работы с пользователями"""

    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    key = models.CharField(max_length=12, verbose_name='Ключ для верификации почты', **NULLABLE)
    is_verified = models.BooleanField(default=False, verbose_name='Почта верифицирована')
    slug = models.SlugField(unique=True, verbose_name='slug')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.email})'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('pk',)
        permissions = [
            (
                'set_is_active_user',   # Разрешение на блокировку/активацию пользователя
                'Can active Пользователь'
            )
        ]

    def save(self, *args, **kwargs):
        """Создает уникальный slug для пользователя"""

        self.slug = slugify(self.email)
        base_slug = self.slug
        num = 1
        while User.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
            self.slug = f'{base_slug}-{num}'
            num += 1
        super().save(*args, **kwargs)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shrtcut icon" type="image/x-icon" href="{% static 'service/img/favicon.png' %}">
    <title>Сервис рассылки сообщений</title>
    <link rel="stylesheet" type="text/css" href="{% static 'service/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="row bg-primary">
        <div class="col-12">
            <h1 class="text-center text-white">Сервис рассылки сообщений</h1>
        </div>
    </div>
</header>
<div class="row">
    <div class="col-10">
        <div class="p-3 px-4 md-5">
            <nav class="ms-5">
                <a class="p-2 btn btn-outline-primary" href="{% url 'service:home' %}">Главная</a>
                {% if perms.service.view_customer %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'service:customers' %}">Клиенты</a>
                {% endif %}
                {% if perms.service.view_mailing %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'service:mailings' %}">Рассылки</a>
                {% endif %}
                {% if perms.service.view_message %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'service:messages' %}">Сообщения</a>
                {% endif %}
                {% if perms.users.view_user %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_list' %}">Пользователи</a>
                {% endif %}
            </nav>
        </div>
    </div>
    <div class="col-2 px-md-5">
        {% if user.is_authenticated %}
            <div class="dropdown mt-4">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    {{ user }}
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item text-white bg-primary" href="{% url 'users:profile' %}">Профиль</a></li>
                    <li><a class="dropdown-item text-primary" href="{% url 'users:logout' %}">Выход</a></li>
                    {% if not user.is_verified %}
                        <li><a class="dropdown-item text-white bg-danger" href="{% url 'users:verification' %}">Подтвердите
                            электронную
                            почту</a></li>
                    {% endif %}
                </ul>
            </div>
        {% else %}
            <div class="dropdown mt-4">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Вход / Регистрация
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item text-primary" href="{% url 'users:login' %}">Вход</a></li>
                    <li><a class="dropdown-item text-primary" href="{% url 'users:register' %}">Регистрация</a></li>
                </ul>
            </div>
        {% endif %}
    </div>
</div>



{% block content %}
{% endblock %}

<script src="{% static 'service/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>